language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install: "pip install pysam pyvcf pyfasta fisher"
# command to run tests
script: cd example && ./run_test.sh
